### PR TITLE
[example/demo/models.py] Remove non-final SailfishOS releases  (`a.b.c.x`, when an larger `x` exists)

### PR DESCRIPTION
**Pull request by Olf0**

### CODE REVIEW

**Comment by CODeRUS** [comment]
why? nobody care intermediate version in pm, just upgrade to .13

**Comment by Olf0** [comment]
> why? nobody care intermediate version in pm, just upgrade to .13

1. With the same argument you could also omit `4.6.0.11` and all previous EA-releases.
2. Currently all public releases ≥ `1.1.9.23` (including all EA releases) are listed (see your list at [coderus.openrepos.net/whitesoft/sailversion](https://coderus.openrepos.net/whitesoft/sailversion)), except for `4.6.0.12`.
3. Maybe someone really did not yet upgrade from `4.6.0.12`.

So ultimately this is a matter of consistency to the current policy on which releases are listed.

If you really want to change that policy, consequently all releases `a.b.c.*` would have to be omitted except for the final point release `a.b.c.x` of each release `a.b.c`.
<sub>I have a gut feeling that this is not a good idea, even though it appears to be logical and stringent.</sub>

**Comment by CODeRUS** [comment]
yes its good idea in general to remove all minor versions from database, version chooser is unreasonably long.

and rare cases if someone did not upgraded yet can be workarounded by god mode.

**Comment by Olf0** [comment]
Voilà, s'il vous plaît: 1260dfa

**Comment by Olf0** [comment]
Please consider the consequences (it is your code!), e.g. what happens when a Patch references SailfishOS releases, which are not in this list any longer.
Also Jolla might really alter QML files, configuration files and other patchable files between point releases (and probably has done that in the past), so Patches must be able to address a specific point release.

Thinking about it, I am for reverting commit 1260dfa and merge the original version.
The proper solution IMO would be to alter the code *and* list, so that only the first three fields are evaluated (and hence listed), but that still bears aforementioned caveats.

**Comment by CODeRUS** [comment]
Should be safe, this code only for generating versoin chooser in html, existing values inside database are not affected.

**Pull request merged**
